import Head from "next/head";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen w-screen">
        <div className="flex flex-row justify-between items-center h-fit p-5 w-full border-b-2 border-white">
          Next JS Snap
          <ConnectButton />
        </div>
      </div>
    </>
  );
}
